version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: namek
      POSTGRES_DB: users_auth
    ports:
      - "5432:5432"
  auth-service:
    image: authentication-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/users_auth
      # Autres variables d'environnement nécessaires
    depends_on:
      - db
    ports:
      - "8085:8085"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "monemail@example.com"
      PGADMIN_DEFAULT_PASSWORD: "monMotDePasse"
    ports:
      - "443:80"
    depends_on:
      - db
